import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Starting full database seed with 88 products...');

  // --- 1. ADMIN USER ---
  const adminEmail = 'sriramapoojastores@admin.com';
  const passwordHash = await bcrypt.hash('admin123', 10);
  await prisma.user.upsert({
    where: { email: adminEmail },
    update: { passwordHash, role: 'CHIEF_ADMIN', emailVerified: true },
    create: {
      name: 'Sri Rama Pooja Stores Admin',
      email: adminEmail,
      passwordHash,
      role: 'CHIEF_ADMIN',
      emailVerified: true,
    },
  });
  console.log('Admin user created/verified.');

  // --- 2. CATEGORIES ---
  const categoriesData = [
    { name: "Incense & Fragrance", slug: "incense-fragrance", code: "INC" },
    { name: "Diyas & Lamps", slug: "diyas-lamps", code: "DYA" },
    { name: "God Idols & Murtis", slug: "god-idols-murtis", code: "IDL" },
    { name: "Puja Thali & Utensils", slug: "puja-thali-utensils", code: "THD" },
    { name: "Sacred Powders & Offerings", slug: "sacred-powders", code: "PWD" },
    { name: "Flowers & Garlands", slug: "flowers-garlands", code: "FLR" },
    { name: "Sacred Threads & Malas", slug: "sacred-threads-malas", code: "MLA" },
    { name: "Puja Fabrics & Clothes", slug: "puja-fabrics", code: "FAB" },
    { name: "Puja Kits", slug: "puja-kits", code: "KIT" },
    { name: "Sacred Water & Liquids", slug: "sacred-water-liquids", code: "LQD" },
    { name: "Books & Spiritual Items", slug: "books-spiritual-items", code: "SPR" },
    { name: "Temple & Mandir Decoration", slug: "temple-mandir-decoration", code: "DCR" }
  ];

  const categoryMap: Record<string, string> = {};

  for (const cat of categoriesData) {
    const catId = `cat-${cat.code.toLowerCase()}`;
    const createdCat = await prisma.category.upsert({
      where: { id: catId },
      update: { name: cat.name, slug: cat.slug },
      create: {
        id: catId,
        name: cat.name,
        slug: cat.slug,
      },
    });
    categoryMap[cat.name] = createdCat.id;
  }
  console.log('Categories created.');

  // --- 3. PRODUCTS ---
  const productsData = [
    // CATEGORY 1: INCENSE & FRAGRANCE
    {
      sku: "SRP-INC-001",
      name: "Agarbatti (Incense Sticks) — Rose Fragrance",
      categoryName: "Incense & Fragrance",
      subcategory: "Agarbatti",
      description: "Rose-scented agarbatti sticks made with natural flower extracts and bamboo core. Used daily in puja to purify the atmosphere and invite divine presence. Burns for approximately 30–35 minutes per stick.",
      price: 60,
      unit: "Pack of 20 sticks",
      material: "Bamboo + Natural flower extract",
      tags: ["agarbatti", "incense", "rose", "fragrance", "daily puja"],
      festival: ["All festivals"],
      deity: ["All deities"],
      imagePrompt: "A bundle of rose-scented incense sticks tied with a red ribbon, placed in a brass incense holder with a trail of white smoke rising, warm golden background, soft studio lighting, product photography, 4K",
      isFeatured: true
    },
    {
      sku: "SRP-INC-002",
      name: "Agarbatti — Sandalwood (Chandan) Fragrance",
      categoryName: "Incense & Fragrance",
      subcategory: "Agarbatti",
      description: "Pure sandalwood agarbatti crafted from authentic chandan powder. Sandalwood is considered sacred in Hindu tradition and is believed to calm the mind and create a meditative atmosphere during worship.",
      price: 80,
      unit: "Pack of 20 sticks",
      material: "Sandalwood powder + bamboo",
      tags: ["chandan", "sandalwood", "agarbatti", "meditation"],
      festival: ["All"],
      deity: ["Shiva", "Vishnu", "Saraswati"],
      imagePrompt: "Sandalwood incense sticks bundle in natural brown tones, placed beside a small sandalwood chunk, cream background, warm lighting, 4K product photo",
      isFeatured: false
    },
    {
      sku: "SRP-INC-003",
      name: "Agarbatti — Jasmine (Mogra) Fragrance",
      categoryName: "Incense & Fragrance",
      subcategory: "Agarbatti",
      description: "Jasmine scented incense sticks for a sweet and purifying aroma. Invokes the blessings of Goddess Lakshmi.",
      price: 60,
      unit: "Pack of 20 sticks",
      material: "Bamboo + Fragrance",
      tags: ["jasmine", "mogra", "fragrance"],
      festival: ["All"],
      deity: ["Lakshmi", "Devi"],
      imagePrompt: "A bundle of white jasmine incense sticks with a mogra flower nearby, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-INC-004",
      name: "Agarbatti — Camphor (Kapoor) Fragrance",
      categoryName: "Incense & Fragrance",
      subcategory: "Agarbatti",
      description: "Camphor scented agarbatti known for its strong purifying properties. Eliminates negative energy from the space.",
      price: 70,
      unit: "Pack of 20 sticks",
      material: "Bamboo + Camphor essence",
      tags: ["camphor", "kapoor"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A bundle of camphor incense sticks, pure white and brown texture, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-INC-005",
      name: "Dhoop Sticks (Thick Incense Sticks)",
      categoryName: "Incense & Fragrance",
      subcategory: "Dhoop",
      description: "Thick dhoop sticks made from a blend of natural herbs, resins, and cow dung. Produce dense, purifying smoke ideal for yagnas and extended puja ceremonies.",
      price: 50,
      unit: "Pack of 10",
      material: "Natural herbs + cow dung",
      tags: ["dhoop", "thick incense", "havan"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "Thick brown dhoop sticks on a brass dhoop stand with rising white smoke, dark saffron background, sacred atmosphere, product photo 4K",
      isFeatured: false
    },
    {
      sku: "SRP-INC-006",
      name: "Dhoop Cones",
      categoryName: "Incense & Fragrance",
      subcategory: "Dhoop",
      description: "Natural resin dhoop cones that burn evenly to provide a calming environment for meditation and daily rituals.",
      price: 45,
      unit: "Pack of 12 cones",
      material: "Natural resin + herbs",
      tags: ["dhoop cone", "incense cone"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "Several dhoop cones arranged on a metallic plate, one lit with a glowing tip, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-INC-007",
      name: "Sambrani (Benzoin Resin / Lobhan)",
      categoryName: "Incense & Fragrance",
      subcategory: "Sambrani",
      description: "Authentic sambrani resin (lobhan/benzoin) used in South Indian puja and domestic rituals. When placed on hot coals it releases thick purifying smoke believed to ward off negative energy and evil eye.",
      price: 90,
      unit: "50g pack",
      material: "Natural resin",
      tags: ["sambrani", "lobhan", "benzoin", "smoke", "South Indian puja"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "Small amber-brown chunks of sambrani resin on a brass holder with glowing red coal and rising white smoke, dark temple background, 4K",
      isFeatured: false
    },
    {
      sku: "SRP-INC-008",
      name: "Kapoor (Camphor Tablets)",
      categoryName: "Incense & Fragrance",
      subcategory: "Camphor",
      description: "Pure camphor tablets used for aarti, purifying spaces, and offering to deities. Camphor flames are believed to dispel negativity and attract divine blessings.",
      price: 40,
      unit: "Pack of 25 tablets",
      material: "Pure Camphor",
      tags: ["camphor", "kapoor", "aarti", "purification"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "Small white camphor tablets arranged on a brass plate with a lit camphor flame, golden glow, dark background, sacred temple atmosphere, 4K",
      isFeatured: false
    },
    {
      sku: "SRP-INC-009",
      name: "Guggul Dhoop (Herbal Resin Incense)",
      categoryName: "Incense & Fragrance",
      subcategory: "Dhoop",
      description: "Traditional guggul resin known for its powerful spiritual cleansing properties, often used in havan and navratri rituals.",
      price: 120,
      unit: "100g pack",
      material: "Guggul resin",
      tags: ["guggul", "dhoop", "havan", "herbal"],
      festival: ["Navratri", "Diwali"],
      deity: ["All deities"],
      imagePrompt: "A heap of dark guggul resin pieces on a brass tray, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-INC-010",
      name: "Havan Samagri (Sacred Fire Offering Mixture)",
      categoryName: "Incense & Fragrance",
      subcategory: "Havan",
      description: "A traditional blend of 21 sacred herbs, dried flowers, resins and roots used in havan/homa fire rituals. Each ingredient holds Vedic significance for purification, health, and prosperity.",
      price: 150,
      unit: "250g pack",
      material: "Mix of 21+ sacred herbs, roots, resins",
      tags: ["havan", "yagna", "homa", "fire ritual", "Vedic"],
      festival: ["Diwali", "Navratri", "Griha Pravesh", "Satyanarayan Puja"],
      deity: ["All deities"],
      imagePrompt: "A wooden bowl filled with mixed havan samagri herbs and roots, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },

    // CATEGORY 2: DIYAS & LAMPS
    {
      sku: "SRP-DYA-001",
      name: "Clay Diya (Terracotta Oil Lamp) — Pack of 10",
      categoryName: "Diyas & Lamps",
      subcategory: "Diyas",
      description: "Traditional handcrafted terracotta diyas, the most sacred form of lamp in Hindu worship. Fill with oil or ghee and cotton wick to offer light to deities during aarti. Perfect for Diwali and daily puja.",
      price: 50,
      unit: "Pack of 10",
      material: "Terracotta clay",
      tags: ["clay diya", "terracotta", "Diwali", "oil lamp"],
      festival: ["Diwali", "Karthika Masam", "all festivals"],
      deity: ["All deities"],
      imagePrompt: "10 small terracotta clay diyas arranged in a circle with lit cotton wicks, warm golden light, dark background, Diwali atmosphere, product photo 4K",
      isFeatured: true
    },
    {
      sku: "SRP-DYA-002",
      name: "Brass Diya (Single Wick)",
      categoryName: "Diyas & Lamps",
      subcategory: "Diyas",
      description: "Elegant single-wick brass diya with a deep oil cup for long-lasting illumination. Brass is considered sacred in Hinduism for its ability to hold spiritual vibrations. Ideal for daily mandir use.",
      price: 250,
      unit: "1 piece",
      material: "Pure Brass",
      weight: "150g",
      tags: ["brass diya", "lamp", "mandir", "aarti"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A polished brass single-wick diya with a lit flame, placed on a red cloth, golden reflection, soft warm studio light, product photography 4K",
      isFeatured: false
    },
    {
      sku: "SRP-DYA-003",
      name: "Brass Panchmukhi Diya (5-Wick Oil Lamp)",
      categoryName: "Diyas & Lamps",
      subcategory: "Diyas",
      description: "Five-flame brass diya representing the five elements (Pancha Bhuta). The Panchmukhi diya is lit during major puja and aarti ceremonies for maximum divine illumination and spiritual significance.",
      price: 450,
      unit: "1 piece",
      material: "Brass",
      weight: "350g",
      tags: ["panchmukhi", "5 wick", "brass", "aarti"],
      festival: ["Diwali", "Navratri", "Ganesh Chaturthi"],
      deity: ["All deities"],
      imagePrompt: "A gleaming brass 5-wick panchmukhi diya with all wicks lit, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-DYA-004",
      name: "Copper Diya",
      categoryName: "Diyas & Lamps",
      subcategory: "Diyas",
      description: "Pure copper oil lamp for puja. Copper is revered in Ayurveda and Hindu tradition for its purifying properties. Ideal for Lakshmi and Surya worship.",
      price: 180,
      unit: "1 piece",
      material: "Pure Copper",
      tags: ["copper diya", "Lakshmi", "Surya puja"],
      festival: ["All"],
      deity: ["Lakshmi", "Surya"],
      imagePrompt: "A shiny copper diya with a lit wick, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-DYA-005",
      name: "Akhand Diya (Continuous Burning Lamp)",
      categoryName: "Diyas & Lamps",
      subcategory: "Diyas",
      description: "A large, deep brass lamp designed for continuous (akhand) burning during festivals and auspicious occasions. Can hold enough oil to burn uninterrupted for 24+ hours.",
      price: 550,
      unit: "1 piece",
      material: "Brass",
      weight: "500g",
      tags: ["akhand diya", "continuous lamp", "festival"],
      festival: ["Navratri", "Karthika"],
      deity: ["All deities"],
      imagePrompt: "A large brass akhand diya with a glass cover, lit flame inside, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-DYA-006",
      name: "Earthen Diya with Painted Designs — Diwali Special (Pack of 6)",
      categoryName: "Diyas & Lamps",
      subcategory: "Diyas",
      description: "Beautifully hand-painted earthen diyas designed specifically for Diwali decorations to bring color and light to your home.",
      price: 120,
      unit: "Pack of 6",
      material: "Clay with acrylic paint",
      tags: ["decorative diya", "Diwali"],
      festival: ["Diwali"],
      deity: ["All deities"],
      imagePrompt: "A set of 6 colorful hand-painted clay diyas arranged beautifully, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-DYA-007",
      name: "Lotus-Shaped Brass Diya (Kamal Deep)",
      categoryName: "Diyas & Lamps",
      subcategory: "Diyas",
      description: "Intricately designed brass diya shaped like a blooming lotus, the symbol of Goddess Lakshmi and spiritual awakening.",
      price: 380,
      unit: "1 piece",
      material: "Brass",
      tags: ["lotus diya", "Lakshmi", "kamal deep"],
      festival: ["All"],
      deity: ["Lakshmi"],
      imagePrompt: "A brass diya carved in the shape of a lotus flower, lit wick in center, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-DYA-008",
      name: "Deepam Oil (Pure Sesame / Til Oil for Lamps)",
      categoryName: "Diyas & Lamps",
      subcategory: "Lamp Oil",
      description: "Pure sesame oil specifically extracted for lighting deepams. Burns cleanly and produces a divine fragrance.",
      price: 120,
      unit: "500ml bottle",
      material: "Pure sesame oil",
      tags: ["lamp oil", "sesame oil", "deepam"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A clear plastic bottle filled with golden sesame deepam oil, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-DYA-009",
      name: "Cotton Wicks (Batti) for Diya — Round",
      categoryName: "Diyas & Lamps",
      subcategory: "Wicks",
      description: "Hand-rolled pure cotton round wicks for daily diya lighting. Easy to soak and long-lasting.",
      price: 30,
      unit: "Pack of 100 wicks",
      material: "Pure cotton",
      tags: ["cotton wick", "batti", "diya wick"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A small packet of white fluffy round cotton wicks, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-DYA-010",
      name: "Ghee for Diya (Pure Cow Ghee)",
      categoryName: "Diyas & Lamps",
      subcategory: "Lamp Fuel",
      description: "Pure cow ghee intended solely for lighting diyas and havan. Emits highly purifying smoke when burned.",
      price: 350,
      unit: "500g jar",
      material: "Pure cow ghee",
      tags: ["ghee", "lamp fuel", "sacred"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A glass jar filled with rich yellow cow ghee, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: true
    },

    // CATEGORY 3: GOD IDOLS & MURTIS
    {
      sku: "SRP-IDL-001",
      name: "Ganesha Idol — Brass (4 inch)",
      categoryName: "God Idols & Murtis",
      subcategory: "Idols",
      description: "Beautifully crafted brass idol of Lord Ganesha in seated position with his vahana mouse at the base. Ganesha is worshipped as the remover of obstacles and is the first deity invoked in any Hindu ritual.",
      price: 850,
      unit: "1 piece",
      material: "Brass",
      dimensions: "10cm H",
      tags: ["Ganesha", "Ganpati", "brass murti", "idol"],
      festival: ["Ganesh Chaturthi", "all festivals"],
      deity: ["Ganesha"],
      imagePrompt: "A 4-inch shining brass Ganesha idol in seated position, intricate detailing, trunk curved left, placed on a red velvet cloth, white background, studio product photography, 4K",
      isFeatured: true
    },
    {
      sku: "SRP-IDL-002",
      name: "Lakshmi Idol — Brass (4 inch)",
      categoryName: "God Idols & Murtis",
      subcategory: "Idols",
      description: "Goddess Lakshmi brass idol in standing pose with lotus in one hand and coins flowing from the other. Worshipped for wealth, prosperity, and fortune. Essential for Diwali puja and Friday worship.",
      price: 900,
      unit: "1 piece",
      material: "Brass",
      tags: ["Lakshmi", "idol", "brass murti"],
      festival: ["Diwali", "Varalakshmi Vratam"],
      deity: ["Lakshmi"],
      imagePrompt: "A 4-inch shining brass Lakshmi idol holding lotuses, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-IDL-003",
      name: "Shiva Lingam with Nandi — Brass",
      categoryName: "God Idols & Murtis",
      subcategory: "Idols",
      description: "Sacred Shiva Lingam set with the Nandi bull, representing the divine masculine energy and cosmic consciousness. Consecrated for Shiva puja, Mondays, and Mahashivaratri worship.",
      price: 750,
      unit: "1 piece",
      material: "Brass",
      tags: ["Shiva", "Lingam", "Nandi", "idol"],
      festival: ["Mahashivaratri", "Shravan month"],
      deity: ["Shiva"],
      imagePrompt: "A brass Shiva Lingam with a small Nandi bull beside it, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-IDL-004",
      name: "Krishna Idol (Bal Gopal / Laddu Gopal) — Brass",
      categoryName: "God Idols & Murtis",
      subcategory: "Idols",
      description: "Adorable brass idol of baby Krishna (Laddu Gopal), commonly dressed and worshipped daily in Hindu households.",
      price: 680,
      unit: "1 piece",
      material: "Brass",
      tags: ["Krishna", "Bal Gopal", "Laddu Gopal", "idol"],
      festival: ["Janmashtami"],
      deity: ["Krishna"],
      imagePrompt: "A cute brass idol of baby Krishna crawling with a butter ball, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-IDL-005",
      name: "Saraswati Idol — Brass",
      categoryName: "God Idols & Murtis",
      subcategory: "Idols",
      description: "Brass idol of Goddess Saraswati playing the veena, worshipped for knowledge, music, and wisdom.",
      price: 850,
      unit: "1 piece",
      material: "Brass",
      tags: ["Saraswati", "idol", "knowledge"],
      festival: ["Saraswati Puja", "Basant Panchami"],
      deity: ["Saraswati"],
      imagePrompt: "A beautifully detailed brass Saraswati idol holding a veena, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-IDL-006",
      name: "Durga / Devi Idol — Brass",
      categoryName: "God Idols & Murtis",
      subcategory: "Idols",
      description: "Powerful brass idol of Goddess Durga seated on her lion mount, holding various weapons to destroy evil.",
      price: 950,
      unit: "1 piece",
      material: "Brass",
      tags: ["Durga", "Devi", "idol", "power"],
      festival: ["Navratri", "Durga Puja"],
      deity: ["Durga", "Devi"],
      imagePrompt: "A majestic brass Durga idol riding a lion, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-IDL-007",
      name: "Rama Parivar Idol Set (Ram, Sita, Lakshmana, Hanuman)",
      categoryName: "God Idols & Murtis",
      subcategory: "Idols",
      description: "Complete brass set of Rama Parivar representing ideal family and devotion. Highly auspicious for home mandirs.",
      price: 1800,
      unit: "Set of 4 idols",
      material: "Brass",
      tags: ["Rama", "Sita", "Parivar", "idol set"],
      festival: ["Ram Navami", "Diwali"],
      deity: ["Rama", "Sita", "Hanuman"],
      imagePrompt: "A brass idol set of Rama, Sita, Lakshmana standing, and Hanuman kneeling, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-IDL-008",
      name: "Hanuman Idol — Brass (Standing Pose)",
      categoryName: "God Idols & Murtis",
      subcategory: "Idols",
      description: "Standing brass idol of Lord Hanuman, the supreme devotee of Lord Rama, worshipped for strength and courage.",
      price: 720,
      unit: "1 piece",
      material: "Brass",
      tags: ["Hanuman", "idol", "strength"],
      festival: ["Hanuman Jayanti", "Tuesday puja"],
      deity: ["Hanuman"],
      imagePrompt: "A brass Hanuman idol standing with a mace, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-IDL-009",
      name: "Navagraha Idol Set (9 Planet Deities)",
      categoryName: "God Idols & Murtis",
      subcategory: "Idols",
      description: "Set of nine planetary deities (Navagraha) in brass, used to pacify planetary doshas in Vedic astrology.",
      price: 2500,
      unit: "Set of 9",
      material: "Brass",
      tags: ["navagraha", "9 planets", "Vedic astrology"],
      festival: ["All"],
      deity: ["Navagraha"],
      imagePrompt: "A set of 9 small brass idols representing the Navagraha on a single platform, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-IDL-010",
      name: "Panchadhatu (5-Metal Alloy) Ganesha Idol",
      categoryName: "God Idols & Murtis",
      subcategory: "Idols",
      description: "Highly auspicious Ganesha idol made from panchadhatu, a sacred five-metal alloy according to Vedic tradition. Believed to radiate maximum positive energy and divine vibrations.",
      price: 1200,
      unit: "1 piece",
      material: "Panchadhatu (gold, silver, copper, zinc, iron alloy)",
      tags: ["panchadhatu", "Ganesha", "alloy idol"],
      festival: ["Ganesh Chaturthi"],
      deity: ["Ganesha"],
      imagePrompt: "A multi-toned metallic Ganesha idol made of panchadhatu, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },

    // CATEGORY 4: PUJA THALI & UTENSILS
    {
      sku: "SRP-THD-001",
      name: "Puja Thali Set — Brass (7-piece)",
      categoryName: "Puja Thali & Utensils",
      subcategory: "Thali Sets",
      description: "Complete 7-piece brass puja thali set including thali plate, diya, bell, incense holder, kumkum container, small bowl, and spoon. Everything needed for daily worship beautifully arranged on one plate.",
      price: 1200,
      unit: "1 set",
      material: "Brass",
      tags: ["thali", "puja set", "brass", "complete set"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "An ornate brass puja thali with 7 items arranged on it — diya, bell, kumkum container, small bowl, incense holder, spoon, on a red cloth background, golden light, product photography 4K",
      isFeatured: true
    },
    {
      sku: "SRP-THD-002",
      name: "Puja Bell (Ghanti) — Brass",
      categoryName: "Puja Thali & Utensils",
      subcategory: "Utensils",
      description: "Pure brass puja bell (ghanti) with a wooden handle. The ringing of the bell during puja is believed to invoke divine presence and drive away evil spirits. Its resonant sound purifies the surrounding atmosphere.",
      price: 250,
      unit: "1 piece",
      material: "Brass",
      weight: "200g",
      tags: ["ghanti", "bell", "brass", "aarti"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A pure brass hand bell with intricate carvings, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-THD-003",
      name: "Kalash (Sacred Copper Pot) — Copper",
      categoryName: "Puja Thali & Utensils",
      subcategory: "Utensils",
      description: "Traditional copper kalash used in all Hindu ceremonies. Filled with water or panchamrit and decorated with mango leaves and coconut, the kalash symbolizes Goddess Lakshmi and cosmic abundance.",
      price: 450,
      unit: "1 piece",
      material: "Pure Copper",
      tags: ["kalash", "copper pot", "mangal kalash", "ceremony"],
      festival: ["All"],
      deity: ["Lakshmi", "All deities"],
      imagePrompt: "A polished copper kalash pot, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-THD-004",
      name: "Puja Spoon (Udharini / Achamani Spoon) — Brass",
      categoryName: "Puja Thali & Utensils",
      subcategory: "Utensils",
      description: "Small brass spoon used to offer water during puja and abhishekam.",
      price: 120,
      unit: "1 piece",
      material: "Brass",
      tags: ["spoon", "achamani", "abhishekam"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A small traditional brass puja spoon, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-THD-005",
      name: "Panchamrit Bowl Set — Brass",
      categoryName: "Puja Thali & Utensils",
      subcategory: "Utensils",
      description: "Set of 5 small brass bowls (panch patra) for holding the five sacred offerings: milk, curd, honey, ghee, and sugar. Used in abhishekam rituals for bathing idols.",
      price: 650,
      unit: "Set of 5 bowls",
      material: "Brass",
      tags: ["panchamrit", "abhishekam", "5 bowls"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A set of 5 small matching brass bowls arranged in a curve, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-THD-006",
      name: "Puja Chowki (Wooden Altar Table)",
      categoryName: "Puja Thali & Utensils",
      subcategory: "Furniture",
      description: "Handcrafted sheesham wood chowki (low platform) for placing idols and puja items. Carved with traditional motifs. Provides an elevated sacred platform for deities during worship.",
      price: 850,
      unit: "1 piece",
      material: "Sheesham wood",
      dimensions: "30x30x15cm",
      tags: ["chowki", "wooden altar", "mandir platform"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A low square wooden chowki with carved borders and small legs, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-THD-007",
      name: "Aarti Plate (Stand-Alone Brass Plate)",
      categoryName: "Puja Thali & Utensils",
      subcategory: "Thali Sets",
      description: "A simple, elegant brass plate specifically used for performing aarti and carrying floral offerings.",
      price: 300,
      unit: "1 piece",
      material: "Brass",
      tags: ["aarti plate", "brass plate"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A clean, empty polished brass plate, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-THD-008",
      name: "Havan Kund (Fire Pit for Yagna) — Copper",
      categoryName: "Puja Thali & Utensils",
      subcategory: "Havan",
      description: "A traditional copper square pyramid structure used to hold the sacred fire during havan and yagna ceremonies.",
      price: 2200,
      unit: "1 piece",
      material: "Copper",
      dimensions: "20x20x20cm",
      tags: ["havan kund", "yagna", "fire ritual", "copper"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A pyramid-shaped copper havan kund with stepped sides, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-THD-009",
      name: "Agarbatti Stand / Incense Holder — Brass",
      categoryName: "Puja Thali & Utensils",
      subcategory: "Holders",
      description: "A brass stand that securely holds multiple incense sticks, preventing ash from falling on the altar.",
      price: 150,
      unit: "1 piece",
      material: "Brass",
      tags: ["agarbatti holder", "incense stand"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A brass agarbatti stand with multiple holes for sticks, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-THD-010",
      name: "Kumkum Box Set (Haldi + Kumkum Container) — Brass",
      categoryName: "Puja Thali & Utensils",
      subcategory: "Containers",
      description: "A beautifully crafted twin brass container attached together, specifically designed to hold haldi and kumkum.",
      price: 280,
      unit: "1 set (2 containers)",
      material: "Brass",
      tags: ["kumkum", "haldi", "container"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A twin brass container joined in the middle, one filled with red kumkum and the other with yellow haldi, soft studio lighting, 4K resolution",
      isFeatured: false
    },

    // CATEGORY 5: SACRED POWDERS & OFFERINGS
    {
      sku: "SRP-PWD-001",
      name: "Kumkum (Red Vermilion Powder)",
      categoryName: "Sacred Powders & Offerings",
      subcategory: "Powders",
      description: "Pure red kumkum powder used for tilak on forehead and as offering to Devi and Lakshmi. An essential part of every puja, wedding, and auspicious occasion in Hindu tradition.",
      price: 50,
      unit: "50g pack",
      material: "Natural powder",
      tags: ["kumkum", "vermilion", "tilak", "red powder"],
      festival: ["All"],
      deity: ["Lakshmi", "Devi"],
      imagePrompt: "A pile of bright red kumkum powder on a silver plate, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-PWD-002",
      name: "Haldi (Turmeric Powder) — Puja Grade",
      categoryName: "Sacred Powders & Offerings",
      subcategory: "Powders",
      description: "Pure, high-quality turmeric powder for ritual use. Applied as tilak and used in purification rituals, haldi ceremonies, and offerings. Considered auspicious and purifying in Hindu culture.",
      price: 60,
      unit: "100g pack",
      material: "Turmeric",
      tags: ["haldi", "turmeric", "puja", "purification"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A small brass bowl filled with vibrant yellow turmeric powder, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-PWD-003",
      name: "Chandan Powder (Sandalwood Powder)",
      categoryName: "Sacred Powders & Offerings",
      subcategory: "Powders",
      description: "Pure white sandalwood powder used for making chandan paste for tilak. Known for its cooling effect.",
      price: 120,
      unit: "50g pack",
      material: "Pure white sandalwood",
      tags: ["chandan", "sandalwood", "tilak", "cooling"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A pile of fine white sandalwood powder, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-PWD-004",
      name: "Sindoor (Red Vermilion for Married Women)",
      categoryName: "Sacred Powders & Offerings",
      subcategory: "Powders",
      description: "Traditional bright red sindoor offered to Goddesses and worn by married women.",
      price: 80,
      unit: "10g box",
      material: "Natural powder",
      tags: ["sindoor", "married women", "Devi", "Lakshmi"],
      festival: ["Navratri"],
      deity: ["Devi", "Lakshmi"],
      imagePrompt: "A small ornate box filled with bright red sindoor, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-PWD-005",
      name: "Vibhuti / Bhasma (Sacred Ash)",
      categoryName: "Sacred Powders & Offerings",
      subcategory: "Powders",
      description: "Sacred ash (vibhuti) used in Shaivite tradition. Applied to forehead as three horizontal lines representing Lord Shiva's trident. Made from burned cow dung and sacred herbs.",
      price: 70,
      unit: "50g pack",
      material: "Ash",
      tags: ["vibhuti", "bhasma", "Shiva", "ash", "tilak"],
      festival: ["Mahashivaratri"],
      deity: ["Shiva"],
      imagePrompt: "Fine grey vibhuti ash in a small wooden bowl, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-PWD-006",
      name: "Akshat (Sacred Rice) — Puja Grains",
      categoryName: "Sacred Powders & Offerings",
      subcategory: "Grains",
      description: "Unbroken rice grains mixed with haldi/kumkum, used as a primary offering (akshat) in all Hindu rituals.",
      price: 40,
      unit: "200g pack",
      material: "Rice",
      tags: ["akshat", "rice", "offering", "puja grains"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "Unbroken white rice grains mixed with yellow haldi on a brass plate, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-PWD-007",
      name: "Chandan Paste (Liquid Sandalwood Paste)",
      categoryName: "Sacred Powders & Offerings",
      subcategory: "Pastes",
      description: "Ready-to-use liquid sandalwood paste for applying tilak and performing abhishekam.",
      price: 150,
      unit: "100ml bottle",
      material: "Sandalwood paste",
      tags: ["chandan paste", "sandalwood", "abhishekam"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A small bottle of creamy sandalwood paste, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-PWD-008",
      name: "Gulal (Festival Color Powder) — Holi Special",
      categoryName: "Sacred Powders & Offerings",
      subcategory: "Powders",
      description: "Skin-friendly, natural gulal powder for celebrating Holi and offering to deities.",
      price: 80,
      unit: "100g pack",
      material: "Natural colored powder",
      tags: ["gulal", "color", "holi"],
      festival: ["Holi"],
      deity: ["Krishna"],
      imagePrompt: "A burst of pink and yellow gulal powder, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-PWD-009",
      name: "Rangoli Color Powder Set (10 Colors)",
      categoryName: "Sacred Powders & Offerings",
      subcategory: "Powders",
      description: "Set of 10 vibrant rangoli colors for drawing auspicious patterns at the entrance of the home during festivals.",
      price: 250,
      unit: "Set of 10 packs",
      material: "Color powder",
      tags: ["rangoli", "colors", "decoration"],
      festival: ["Diwali", "Navratri", "Onam", "all festivals"],
      deity: ["All deities"],
      imagePrompt: "Ten small transparent packets of brightly colored rangoli powder, arranged in a circle, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-PWD-010",
      name: "Gorochana (Sacred Yellow Mineral for Tilak)",
      categoryName: "Sacred Powders & Offerings",
      subcategory: "Powders",
      description: "A highly rare and sacred yellow mineral traditionally used for specialized tilaks in Vaishnava traditions.",
      price: 200,
      unit: "10g pack",
      material: "Mineral",
      tags: ["gorochana", "yellow tilak", "rare", "Vaishnava"],
      festival: ["All"],
      deity: ["Vishnu"],
      imagePrompt: "A small packet containing bright yellow gorochana mineral, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },

    // CATEGORY 6: FLOWERS & GARLANDS
    {
      sku: "SRP-FLR-001",
      name: "Artificial Marigold Garland (Toran) — 5 Feet",
      categoryName: "Flowers & Garlands",
      subcategory: "Garlands",
      description: "Vibrant yellow-orange artificial marigold garland for door torans and mandir decoration. Reusable, fade-resistant, and perfect for year-round festival decorations without wilting.",
      price: 180,
      unit: "1 piece (5 ft)",
      material: "Artificial fabric flowers",
      tags: ["marigold", "toran", "garland", "decoration"],
      festival: ["All festivals"],
      deity: ["All deities"],
      imagePrompt: "A long, vibrant orange and yellow artificial marigold garland gracefully draped, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-FLR-002",
      name: "Artificial Lotus Flower Garland",
      categoryName: "Flowers & Garlands",
      subcategory: "Garlands",
      description: "Beautiful artificial pink lotus flower garland specifically used for decorating Goddess Lakshmi and Saraswati idols.",
      price: 220,
      unit: "1 piece",
      material: "Artificial fabric flowers",
      tags: ["lotus", "garland", "decoration"],
      festival: ["All"],
      deity: ["Lakshmi", "Saraswati"],
      imagePrompt: "A stunning garland made of artificial pink lotus flowers, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-FLR-003",
      name: "Door Toran / Bandarwal (Mango Leaf Design)",
      categoryName: "Flowers & Garlands",
      subcategory: "Toran",
      description: "A traditional door hanging (bandarwal) featuring artificial mango leaves, considered highly auspicious for the main entrance.",
      price: 150,
      unit: "1 piece",
      material: "Fabric/artificial",
      tags: ["toran", "door decoration", "auspicious"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "An artificial green mango leaf toran designed to be hung over a doorway, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-FLR-004",
      name: "Tulsi Plant (Sacred Basil) — Artificial",
      categoryName: "Flowers & Garlands",
      subcategory: "Plants",
      description: "Artificial Tulsi (Holy Basil) plant with pot for mandir decoration. Tulsi is considered the most sacred plant in Hinduism and is especially dear to Lord Vishnu and Krishna.",
      price: 350,
      unit: "1 pot (artificial)",
      material: "Artificial",
      tags: ["tulsi", "holy basil", "sacred plant"],
      festival: ["All"],
      deity: ["Vishnu", "Krishna"],
      imagePrompt: "A highly realistic artificial green Tulsi plant in a small decorated terracotta pot, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-FLR-005",
      name: "Flower Petals (Dried Rose Petals for Puja) — 50g",
      categoryName: "Flowers & Garlands",
      subcategory: "Flowers",
      description: "Naturally dried rose petals used for sprinkling on deities, offering during aarti, and decorating the puja thali.",
      price: 90,
      unit: "50g pack",
      material: "Dried flowers",
      tags: ["rose petals", "offering"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A heap of deep red dried rose petals, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },

    // CATEGORY 7: SACRED THREADS & MALAS
    {
      sku: "SRP-MLA-001",
      name: "Rudraksha Mala (108 Beads)",
      categoryName: "Sacred Threads & Malas",
      subcategory: "Malas",
      description: "Authentic 108-bead Rudraksha mala for japa meditation and wearing. Rudraksha beads are the sacred tears of Lord Shiva and are believed to carry immense spiritual power, protection, and healing energy.",
      price: 550,
      unit: "1 mala",
      material: "Natural Rudraksha beads",
      tags: ["rudraksha", "mala", "japa", "Shiva", "108 beads"],
      festival: ["Mahashivaratri"],
      deity: ["Shiva"],
      imagePrompt: "108 brown natural Rudraksha bead mala coiled on a white marble surface, one large guru bead visible, soft natural lighting, product photography 4K",
      isFeatured: true
    },
    {
      sku: "SRP-MLA-002",
      name: "Tulsi Mala (Holy Basil Bead Necklace — 108 Beads)",
      categoryName: "Sacred Threads & Malas",
      subcategory: "Malas",
      description: "Mala crafted from dried Tulsi wood, traditionally worn by Vaishnavas and used for chanting the Hare Krishna mantra.",
      price: 250,
      unit: "1 mala",
      material: "Dried Tulsi wood beads",
      tags: ["tulsi", "mala", "chanting"],
      festival: ["Janmashtami"],
      deity: ["Vishnu", "Krishna"],
      imagePrompt: "A delicate mala made of small, light-brown Tulsi wood beads, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-MLA-003",
      name: "Sphatik Mala (Crystal Quartz Mala — 108 Beads)",
      categoryName: "Sacred Threads & Malas",
      subcategory: "Malas",
      description: "Clear quartz (sphatik) mala known for its cooling properties. Highly recommended for Goddess worship and chanting Devi mantras.",
      price: 750,
      unit: "1 mala",
      material: "Natural crystal quartz",
      tags: ["crystal", "sphatik", "mala", "Devi"],
      festival: ["Navratri"],
      deity: ["Devi"],
      imagePrompt: "A transparent crystal sphatik mala catching the light, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-MLA-004",
      name: "Chandan Mala (Sandalwood Bead Mala)",
      categoryName: "Sacred Threads & Malas",
      subcategory: "Malas",
      description: "A beautifully fragrant mala made from pure sandalwood beads, used to calm the mind during meditation.",
      price: 480,
      unit: "1 mala",
      material: "Sandalwood beads",
      tags: ["chandan", "sandalwood mala"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A smooth, light-brown sandalwood bead mala, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-MLA-005",
      name: "Janeu / Yagnopavit (Sacred Thread)",
      categoryName: "Sacred Threads & Malas",
      subcategory: "Threads",
      description: "Pure cotton sacred thread (janeu/yagnopavit) worn by Brahmin men across the left shoulder. An essential part of upanayana ceremony and daily puja. Represents initiation into Vedic learning.",
      price: 60,
      unit: "Pack of 5",
      material: "100% pure cotton",
      tags: ["janeu", "yagnopavit", "sacred thread", "brahmin", "upanayana"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A pure white circular cotton janeu thread laid flat, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-MLA-006",
      name: "Mauli / Kalava (Red Sacred Thread for Wrist)",
      categoryName: "Sacred Threads & Malas",
      subcategory: "Threads",
      description: "Sacred red and yellow cotton thread tied on the wrist during puja to invoke divine protection and blessings.",
      price: 40,
      unit: "Pack of 5 rolls",
      material: "Cotton + red dye",
      tags: ["mauli", "kalava", "red thread", "protection"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A spool of bright red and yellow intertwined kalava cotton thread, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-MLA-007",
      name: "Gomukhi Bag (Japa Bag for Mala)",
      categoryName: "Sacred Threads & Malas",
      subcategory: "Bags",
      description: "A traditional cloth bag shaped like a cow's face (gomukhi) used to conceal and protect the mala while chanting.",
      price: 120,
      unit: "1 piece",
      material: "Cotton or velvet",
      tags: ["gomukhi", "japa bag", "mala bag"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A saffron-colored cloth gomukhi bag with an embroidered Om symbol, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },

    // CATEGORY 8: PUJA FABRICS & CLOTHES
    {
      sku: "SRP-FAB-001",
      name: "Puja Asana / Mat (Red Velvet)",
      categoryName: "Puja Fabrics & Clothes",
      subcategory: "Mats",
      description: "Thick red velvet puja asana (sitting mat) for meditation and worship. Traditionally used by the priest or devotee performing puja to sit on a sacred, clean surface and absorb divine energy during rituals.",
      price: 350,
      unit: "1 piece",
      material: "Velvet + cotton backing",
      dimensions: "60x90cm",
      tags: ["asana", "puja mat", "sitting mat", "velvet"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A rectangular red velvet mat with an intricate golden border, laid flat, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-FAB-002",
      name: "Mandir Backdrop Cloth (God Photo Frame Cover) — Red/Gold",
      categoryName: "Puja Fabrics & Clothes",
      subcategory: "Cloths",
      description: "Rich red satin cloth with a golden zari border, perfect for placing behind idols or draping over photo frames in the mandir.",
      price: 280,
      unit: "1 piece",
      material: "Satin + zari border",
      tags: ["backdrop", "mandir cloth", "satin"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A shiny red satin cloth with a heavy golden zari border, softly draped, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-FAB-003",
      name: "Chunri / Dupatta for Devi (Red Velvet with Gold Border)",
      categoryName: "Puja Fabrics & Clothes",
      subcategory: "Cloths",
      description: "A beautiful mini red velvet chunri embellished with gold, offered to Goddesses to adorn their idols during Navratri and festivals.",
      price: 450,
      unit: "1 piece",
      material: "Velvet",
      tags: ["chunri", "dupatta"],
      festival: ["Navratri"],
      deity: ["Devi", "Lakshmi", "Durga"],
      imagePrompt: "A small, heavily embellished red velvet chunri with golden sequins and border, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-FAB-004",
      name: "White Dhoti with Angavastram (for Puja Wear)",
      categoryName: "Puja Fabrics & Clothes",
      subcategory: "Clothes",
      description: "Traditional pure cotton white dhoti and matching shoulder cloth (angavastram), standard attire for men performing Vedic rituals.",
      price: 550,
      unit: "1 set",
      material: "100% cotton",
      tags: ["dhoti", "angavastram", "priest wear"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A neatly folded white cotton dhoti with a gold border alongside a matching angavastram, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-FAB-005",
      name: "Navgraha Altar Cloth Set (9 Planet Cloths)",
      categoryName: "Puja Fabrics & Clothes",
      subcategory: "Cloths",
      description: "A set of 9 small square cloths in different colors, each corresponding to one of the nine planetary deities for Navgraha puja.",
      price: 600,
      unit: "Set of 9 cloths",
      material: "Cotton",
      tags: ["navgraha", "9 planets", "altar cloth"],
      festival: ["All"],
      deity: ["Navagraha"],
      imagePrompt: "A set of 9 brightly colored square cotton cloths folded neatly, soft studio lighting, 4K resolution",
      isFeatured: false
    },

    // CATEGORY 9: PUJA KITS
    {
      sku: "SRP-KIT-001",
      name: "Satyanarayan Puja Kit (Complete Set)",
      categoryName: "Puja Kits",
      subcategory: "Kits",
      description: "Complete readymade kit for performing Satyanarayan Puja at home. Includes all required items: kumkum, haldi, agarbatti, camphor, akshat, panchamrit ingredients, sacred thread, and puja instructions booklet.",
      price: 850,
      unit: "1 kit",
      tags: ["Satyanarayan", "puja kit", "complete set"],
      festival: ["Monthly/full moon"],
      deity: ["Vishnu"],
      imagePrompt: "A beautifully arranged Satyanarayan puja kit with all items laid out on a red cloth — incense, camphor, kumkum, haldi, flowers, brass diya, product photography, warm light, 4K",
      isFeatured: true
    },
    {
      sku: "SRP-KIT-002",
      name: "Diwali Puja Kit (Lakshmi-Ganesha Set)",
      categoryName: "Puja Kits",
      subcategory: "Kits",
      description: "Premium Diwali puja kit with Lakshmi-Ganesha idols, decorated thali, diyas, kapoor, rangoli colors, agarbatti, akshat, kumkum, and haldi. Everything needed for the Diwali night puja in one gift-ready box.",
      price: 1200,
      unit: "1 kit",
      tags: ["Diwali", "puja kit", "Lakshmi"],
      festival: ["Diwali"],
      deity: ["Lakshmi", "Ganesha"],
      imagePrompt: "A decorated red box containing Lakshmi Ganesha idols and all puja essentials, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: true
    },
    {
      sku: "SRP-KIT-003",
      name: "Ganesh Chaturthi Puja Kit",
      categoryName: "Puja Kits",
      subcategory: "Kits",
      description: "Complete kit for inviting Lord Ganesha into your home, including clay idol, modak mix, durva grass, and all puja samagri.",
      price: 950,
      unit: "1 kit",
      tags: ["Ganesha", "Chaturthi"],
      festival: ["Ganesh Chaturthi"],
      deity: ["Ganesha"],
      imagePrompt: "A puja kit specifically for Ganesh Chaturthi with a small clay idol surrounded by items, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-KIT-004",
      name: "Navratri Puja Kit",
      categoryName: "Puja Kits",
      subcategory: "Kits",
      description: "A 9-day Navratri special kit containing chunri, dry fruits, kumkum, and items necessary for Ghatasthapana and daily Devi worship.",
      price: 1100,
      unit: "1 kit",
      tags: ["Navratri", "Devi"],
      festival: ["Navratri"],
      deity: ["Durga", "Devi"],
      imagePrompt: "A colorful Navratri kit featuring a red chunri, coconut, and brass kalash, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-KIT-005",
      name: "Griha Pravesh (Housewarming) Puja Kit",
      categoryName: "Puja Kits",
      subcategory: "Kits",
      description: "A comprehensive kit for new home housewarming ceremonies, including havan samagri, kalash, and threshold decoration items.",
      price: 1500,
      unit: "1 kit",
      tags: ["griha pravesh", "housewarming", "new home"],
      festival: ["Griha Pravesh"],
      deity: ["All deities"],
      imagePrompt: "A large comprehensive housewarming puja kit displayed beautifully, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-KIT-006",
      name: "Varalakshmi Vratam Puja Kit",
      categoryName: "Puja Kits",
      subcategory: "Kits",
      description: "Specially curated South Indian Varalakshmi Vratam kit featuring face of Goddess Lakshmi, sacred threads, and offering items.",
      price: 1350,
      unit: "1 kit",
      tags: ["Varalakshmi", "South Indian"],
      festival: ["Varalakshmi Vratam"],
      deity: ["Lakshmi"],
      imagePrompt: "A South Indian style Varalakshmi puja kit featuring a golden Devi face mask, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-KIT-007",
      name: "Shiva Abhishekam Kit",
      categoryName: "Puja Kits",
      subcategory: "Kits",
      description: "A specialized kit containing vibhuti, rudraksha, bel patra, and panchamrit liquids for bathing the Shiva Lingam.",
      price: 780,
      unit: "1 kit",
      tags: ["Shiva", "abhishekam"],
      festival: ["Mahashivaratri", "Shravan"],
      deity: ["Shiva"],
      imagePrompt: "A Shiva abhishekam kit containing vibhuti, small lingam, and copper pot, soft studio lighting, 4K resolution",
      isFeatured: false
    },

    // CATEGORY 10: SACRED WATER & LIQUIDS
    {
      sku: "SRP-LQD-001",
      name: "Ganga Jal (Holy Ganges Water)",
      categoryName: "Sacred Water & Liquids",
      subcategory: "Liquids",
      description: "Pure, authentic Ganga Jal (sacred water from the River Ganges) sealed in a glass bottle. Used in abhishekam, purification of puja space, and as prasad. Considered the most sacred water in Hindu tradition.",
      price: 120,
      unit: "100ml bottle",
      material: "Sacred water",
      tags: ["Gangajal", "holy water", "Ganga", "purification"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A small sealed glass bottle of clear holy Ganga water with a religious label, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-LQD-002",
      name: "Panchamrit (Abhishekam Liquid Set — 5 ingredients)",
      categoryName: "Sacred Water & Liquids",
      subcategory: "Liquids",
      description: "Readymade panchamrit set containing five sacred liquids: cow milk, curd, honey, ghee, and sugar syrup for performing idol abhishekam. Used in Shiva, Ganesha, Vishnu, and Krishna worship.",
      price: 380,
      unit: "1 kit (5 small bottles)",
      material: "Liquids",
      tags: ["panchamrit", "abhishekam", "milk", "honey", "ghee"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "Five small transparent bottles containing milk, curd, honey, ghee, and sugar syrup, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-LQD-003",
      name: "Rose Water (Gulab Jal) for Puja",
      categoryName: "Sacred Water & Liquids",
      subcategory: "Liquids",
      description: "Distilled rose water used to sprinkle on idols and devotees to create a fragrant and pure environment.",
      price: 150,
      unit: "200ml bottle",
      material: "Rose water",
      tags: ["rose water", "gulab jal", "fragrance", "offering"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A pink-tinted bottle of pure rose water with a rose petal beside it, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-LQD-004",
      name: "Cow Ghee (Pure Desi for Puja)",
      categoryName: "Sacred Water & Liquids",
      subcategory: "Liquids",
      description: "Pure desi cow ghee, highly revered for use in havan, lighting akhand diyas, and making panchamrit. Purest offering to Agni.",
      price: 650,
      unit: "1kg jar",
      material: "Pure cow ghee",
      tags: ["ghee", "cow ghee", "havan", "diya", "offering"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A large glass jar filled with rich yellow desi cow ghee, soft studio lighting, 4K resolution",
      isFeatured: false
    },

    // CATEGORY 11: BOOKS, CALENDARS & SPIRITUAL ITEMS
    {
      sku: "SRP-SPR-001",
      name: "Puja Vidhi Booklet (Step-by-step Puja Guide — Telugu/Hindi/English)",
      categoryName: "Books & Spiritual Items",
      subcategory: "Books",
      description: "Easy-to-follow step-by-step puja instructions booklet available in Telugu, Hindi, and English. Covers daily puja vidhi, festival-specific rituals, and mantras with transliterations for all devotees.",
      price: 80,
      unit: "1 booklet",
      tags: ["puja guide", "booklet", "vidhi", "mantra", "instructions"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A vibrant religious booklet showing images of Hindu Gods on the cover, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-SPR-002",
      name: "Hindu Religious Calendar (Panchangam) — Annual",
      categoryName: "Books & Spiritual Items",
      subcategory: "Calendars",
      description: "Traditional Hindu calendar (Panchangam) detailing daily tithis, nakshatras, auspicious timings (muhurats), and upcoming festival dates.",
      price: 150,
      unit: "1 calendar",
      tags: ["panchangam", "calendar", "tithi", "festival dates", "muhurat"],
      festival: ["Ugadi", "New Year"],
      deity: ["All deities"],
      imagePrompt: "A brightly colored wall-hanging Hindu panchangam calendar, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-SPR-003",
      name: "Spiritual Photo Frames (Laminated God Photos — Various Deities)",
      categoryName: "Books & Spiritual Items",
      subcategory: "Frames",
      description: "Beautifully laminated, framed photos of various Hindu deities, perfect for setting up a home mandir or gifting.",
      price: 120,
      unit: "1 piece (A4 size)",
      tags: ["photo frame", "god photo", "laminated", "mandir"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A framed picture of Lord Ganesha with gold trim, leaning against a white background, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-SPR-004",
      name: "Gomati Chakra (Sacred Shell for Vastu)",
      categoryName: "Books & Spiritual Items",
      subcategory: "Spiritual Items",
      description: "Natural Gomati Chakra shells used in Vastu Shastra and puja to remove negative energy and attract prosperity. Place in the puja room, cash box, or entrance of the home for auspicious effects.",
      price: 250,
      unit: "Set of 11",
      material: "Natural shell",
      tags: ["gomati chakra", "vastu", "shell", "prosperity"],
      festival: ["Diwali"],
      deity: ["Lakshmi"],
      imagePrompt: "11 white spiral-patterned Gomati Chakra shells arranged beautifully on a red cloth, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-SPR-005",
      name: "Yantra (Sri Yantra / Lakshmi Yantra — Copper)",
      categoryName: "Books & Spiritual Items",
      subcategory: "Spiritual Items",
      description: "Sacred geometric design (yantra) engraved on a copper plate, serving as a powerful cosmic magnet for wealth and positivity.",
      price: 450,
      unit: "1 piece",
      material: "Copper",
      tags: ["yantra", "sri yantra", "Lakshmi", "Vastu", "sacred geometry"],
      festival: ["All"],
      deity: ["Lakshmi", "Devi"],
      imagePrompt: "A flat copper plate engraved with complex Sri Yantra geometry, soft studio lighting, 4K resolution",
      isFeatured: false
    },

    // CATEGORY 12: TEMPLE & MANDIR DECORATION
    {
      sku: "SRP-DCR-001",
      name: "Home Mandir / Temple (Wooden, Wall-Mounted)",
      categoryName: "Temple & Mandir Decoration",
      subcategory: "Temples",
      description: "Hand-carved sheesham wood wall-mounted home temple (mandir) with carved pillars, arch, and shelf for idols. Provides a dedicated sacred space for daily worship in the home.",
      price: 3500,
      unit: "1 piece",
      material: "Sheesham wood",
      dimensions: "60x45x30cm",
      tags: ["mandir", "home temple", "wooden temple", "wall mounted"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A small intricately carved wooden wall-hanging temple structure, soft studio lighting, puja store product photography, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-DCR-002",
      name: "Decorative Rangoli Stencil Set",
      categoryName: "Temple & Mandir Decoration",
      subcategory: "Decoration",
      description: "Set of reusable plastic stencils with traditional patterns to easily create beautiful, perfect rangolis at the home entrance.",
      price: 200,
      unit: "Set of 6 stencils",
      material: "Plastic reusable",
      tags: ["rangoli stencil", "Diwali decoration"],
      festival: ["Diwali", "Pongal", "Ugadi"],
      deity: ["All deities"],
      imagePrompt: "Several circular plastic rangoli stencils with intricate cut-out patterns, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-DCR-003",
      name: "Urli Bowl (Brass, for Floating Flowers)",
      categoryName: "Temple & Mandir Decoration",
      subcategory: "Decoration",
      description: "Traditional brass urli bowl used to float flowers, candles, and fragrant oils as a decorative offering. Creates a sacred and serene ambiance in the puja room, living room, or event entrance.",
      price: 1200,
      unit: "1 piece",
      material: "Brass",
      dimensions: "30cm diameter",
      tags: ["urli", "brass bowl", "floating flowers", "decoration"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A wide, shallow brass urli bowl filled with water and floating pink lotus flowers and lit candles, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-DCR-004",
      name: "Backdrop Stand for Mandir (Adjustable)",
      categoryName: "Temple & Mandir Decoration",
      subcategory: "Decoration",
      description: "Adjustable metal stand for holding backdrop cloths securely behind the home altar during festive occasions.",
      price: 2800,
      unit: "1 piece",
      material: "Metal + fabric backdrop",
      tags: ["backdrop stand", "mandir", "photo backdrop"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "An assembled metal backdrop stand with a draped fabric, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-DCR-005",
      name: "Pooja Room Name Plate (Customizable Wood)",
      categoryName: "Temple & Mandir Decoration",
      subcategory: "Decoration",
      description: "Elegant wooden sign reading 'Pooja Room' in beautiful calligraphy to hang on the door of your sacred space.",
      price: 550,
      unit: "1 piece",
      material: "Wood",
      tags: ["name plate", "puja room", "pooja room sign", "wooden"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A polished wooden plaque with 'Pooja Room' engraved in elegant gold lettering, soft studio lighting, 4K resolution",
      isFeatured: false
    },
    {
      sku: "SRP-SUB-001",
      name: "Monthly Puja Essentials Box (Subscription)",
      categoryName: "Puja Kits",
      subcategory: "Subscription",
      description: "Auto-replenishing subscription box containing a month's supply of daily essentials: agarbatti, camphor, kumkum, haldi, and diya wicks.",
      price: 499,
      unit: "1 box",
      material: "Mixed",
      tags: ["subscription", "monthly box", "essentials"],
      festival: ["All"],
      deity: ["All deities"],
      imagePrompt: "A neat cardboard subscription box filled with packets of incense, camphor, wicks, and powders, soft studio lighting, 4K resolution",
      isFeatured: false
    }
  ];

  console.log(`Prepared ${productsData.length} products to insert.`);
  await prisma.product.deleteMany({}); // Optional: clear existing if needed, but we use upsert
  
  let count = 0;
  for (const p of productsData) {
    const categoryId = categoryMap[p.categoryName];
    if (!categoryId) {
      console.warn(`Category not found for product: ${p.name}`);
      continue;
    }

    const slug = p.name.toLowerCase().replace(/ /g, '-').replace(/[^\w-]+/g, '');
    
    await prisma.product.upsert({
      where: { sku: p.sku },
      update: {
        name: p.name,
        slug: slug,
        description: p.description,
        price: p.price,
        stock: 100,
        isAvailable: true,
        isFeatured: p.isFeatured || false,
        categoryId: categoryId,
        subcategory: p.subcategory,
        unit: p.unit,
        material: p.material,
        weight: p.weight ? String(p.weight) : null,
        dimensions: p.dimensions,
        tags: p.tags,
        festival: p.festival,
        deity: p.deity,
        imagePrompt: p.imagePrompt,
      },
      create: {
        sku: p.sku,
        name: p.name,
        slug: slug,
        description: p.description,
        price: p.price,
        stock: 100,
        isAvailable: true,
        isFeatured: p.isFeatured || false,
        categoryId: categoryId,
        subcategory: p.subcategory,
        unit: p.unit,
        material: p.material,
        weight: p.weight ? String(p.weight) : null,
        dimensions: p.dimensions,
        tags: p.tags,
        festival: p.festival,
        deity: p.deity,
        imagePrompt: p.imagePrompt,
        images: {
          create: {
            url: `/images/products/${p.sku}.png`,
            publicId: "local_" + p.sku
          }
        }
      },
    });
    count++;
  }

  console.log(`All ${count} products seeded successfully.`);
  console.log('Seeding completed successfully.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
